"""add passport_number, make insurance_number optional

Revision ID: 01522e999bed
Revises: 74f035f74f31
Create Date: 2026-05-04 16:14:08.872765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01522e999bed'
down_revision = '74f035f74f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('insurance_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_patients_passport_number'), ['passport_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_passport_number'))
        batch_op.alter_column('insurance_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('passport_number')

    # ### end Alembic commands ###
