"""add doctor_directions, direction_id to users, cashier role

Revision ID: 3e3737d7e46b
Revises: f30ee025ac69
Create Date: 2026-04-23 12:30:06.473893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3737d7e46b'
down_revision = 'f30ee025ac69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'doctor_directions', ['direction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('direction_id')

    op.drop_table('doctor_directions')
    # ### end Alembic commands ###
