"""add price to doctor_directions

Revision ID: 40a7e317045e
Revises: a687f972fc3d
Create Date: 2026-04-24 22:00:21.374353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a7e317045e'
down_revision = 'a687f972fc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_directions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_directions', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
