"""add_is_insurance_to_analyses

Revision ID: 5455f9d6ccae
Revises: 01522e999bed
Create Date: 2026-05-05 14:57:40.343677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5455f9d6ccae'
down_revision = '01522e999bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_insurance', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('is_insurance')

    # ### end Alembic commands ###
