"""add_is_insurance_to_doctor_directions

Revision ID: 606477e2c3b7
Revises: 5455f9d6ccae
Create Date: 2026-05-05 15:03:01.581420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606477e2c3b7'
down_revision = '5455f9d6ccae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_directions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_insurance', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_directions', schema=None) as batch_op:
        batch_op.drop_column('is_insurance')

    # ### end Alembic commands ###
