"""user_directions many-to-many

Revision ID: 74f035f74f31
Revises: 40a7e317045e
Create Date: 2026-05-04 15:50:11.620567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74f035f74f31'
down_revision = '40a7e317045e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_directions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['doctor_directions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'direction_id')
    )

    # Migrate existing direction_id data to the new many-to-many table
    conn = op.get_bind()
    rows = conn.execute(sa.text('SELECT id, direction_id FROM users WHERE direction_id IS NOT NULL')).fetchall()
    if rows:
        conn.execute(
            sa.text('INSERT INTO user_directions (user_id, direction_id) VALUES (:uid, :did)'),
            [{'uid': row[0], 'did': row[1]} for row in rows],
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('direction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_ibfk_1'), 'doctor_directions', ['direction_id'], ['id'])

    op.drop_table('user_directions')
    # ### end Alembic commands ###
