"""remove_responsible_from_combined_analyses

Revision ID: 92143591cb14
Revises: 72058c90ae8a
Create Date: 2026-05-05 15:18:53.630567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92143591cb14'
down_revision = '72058c90ae8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_combined_analyses_responsible'), type_='foreignkey')
        batch_op.drop_column('responsible_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_combined_analyses_responsible'), 'users', ['responsible_id'], ['id'])

    # ### end Alembic commands ###
