"""add_combined_analyses

Revision ID: 96568e6a7ae1
Revises: 606477e2c3b7
Create Date: 2026-05-05 15:07:51.302575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96568e6a7ae1'
down_revision = '606477e2c3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combined_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('combined_analysis_items',
    sa.Column('combined_analysis_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['combined_analysis_id'], ['combined_analyses.id'], ),
    sa.PrimaryKeyConstraint('combined_analysis_id', 'analysis_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_analysis_items')
    op.drop_table('combined_analyses')
    # ### end Alembic commands ###
