"""add submission fields to examination_analyses

Revision ID: a338510db77a
Revises: ecd94828a732
Create Date: 2026-04-24 20:13:56.453801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a338510db77a'
down_revision = 'ecd94828a732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_submitted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['submitted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('is_submitted')

    # ### end Alembic commands ###
