"""add visit fields to examination_directions

Revision ID: a687f972fc3d
Revises: a338510db77a
Create Date: 2026-04-24 20:32:30.888408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687f972fc3d'
down_revision = 'a338510db77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination_directions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visited', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('visited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination_directions', schema=None) as batch_op:
        batch_op.drop_column('visited_at')
        batch_op.drop_column('is_visited')

    # ### end Alembic commands ###
