"""add inpatient analysis, tool, blank orders and consultations

Revision ID: a906fb65b85f
Revises: d3e4f5a6b7c8
Create Date: 2026-08-17 14:53:33.481358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a906fb65b85f'
down_revision = 'd3e4f5a6b7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalization_analysis_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospitalization_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('combined_analysis_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_insurance', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_by_id', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['combined_analysis_id'], ['combined_analyses.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospitalization_id'], ['hospitalizations.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitalization_analysis_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitalization_analysis_orders_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_analysis_orders_hospitalization_id'), ['hospitalization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_analysis_orders_status'), ['status'], unique=False)

    op.create_table('hospitalization_blank_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospitalization_id', sa.Integer(), nullable=False),
    sa.Column('blank_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_insurance', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_by_id', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blank_id'], ['blanks.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospitalization_id'], ['hospitalizations.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitalization_blank_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitalization_blank_orders_blank_id'), ['blank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_blank_orders_hospitalization_id'), ['hospitalization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_blank_orders_status'), ['status'], unique=False)

    op.create_table('hospitalization_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospitalization_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_insurance', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_by_id', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['doctor_directions.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospitalization_id'], ['hospitalizations.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitalization_consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitalization_consultations_direction_id'), ['direction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_consultations_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_consultations_hospitalization_id'), ['hospitalization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_consultations_status'), ['status'], unique=False)

    op.create_table('hospitalization_tool_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospitalization_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_insurance', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_by_id', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospitalization_id'], ['hospitalizations.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['analysis_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospitalization_tool_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitalization_tool_orders_hospitalization_id'), ['hospitalization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_tool_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalization_tool_orders_tool_id'), ['tool_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Dropping a table drops its indexes with it. The indexes are left alone on
    # purpose: MySQL keeps a foreign key on its index, so dropping the index
    # first fails with errno 150 and the downgrade never gets to the table.
    op.drop_table('hospitalization_tool_orders')
    op.drop_table('hospitalization_consultations')
    op.drop_table('hospitalization_blank_orders')
    op.drop_table('hospitalization_analysis_orders')
