"""add payment fields to examinations

Revision ID: ecd94828a732
Revises: 7f7ac37447f4
Create Date: 2026-04-24 20:05:20.094281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd94828a732'
down_revision = '7f7ac37447f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['paid_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paid_by_id')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
